### ISSUE TITLE
LinearNoBias not define when train on demo data

### ISSUE THREAD

**Issue by shuguangwang** [harvardnlp/seq2seq-attn#10]
I have setup cuda and torch on an aws gpu instances (ubuntu 14.04). I encountered this error when I tried to train on demo data:

dependent packages are installed as in readme. I tried to add require "util" in train but it did not work. No other code changes were made yet.

ubuntu@ip-xx-xx-xx-xx:/mnt/seq2seq-attn$ th train.lua -data_file data/demo-train.hdf5 -val_data_file data/demo-val.hdf5 -savefile demo-model
loading data...	
done!	
Source vocab size: 28721, Target vocab size: 42787	
Source max sent len: 50, Target max sent len: 52	
/usr/local/bin/luajit: ./models.lua:89: attempt to call field 'LinearNoBias' (a nil value)
stack traceback:
	./models.lua:89: in function 'make_lstm'
	train.lua:545: in function 'main'
	train.lua:584: in main chunk
	[C]: in function 'dofile'
	/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406260
 
Please let me know if i should attach more information.

**Comment by yoonkim** [comment]
it seems like latest version of torch needs 'require util.lua' instead of 'require util'.
Should be fixed now--would you mind trying again?

**Comment by shuguangwang** [comment]
Right, I changed the train.lua and this error is fixed. Now it is another one about luajit overflow, I should have the latest luajit:

ubuntu@ip-xx:/mnt/seq2seq-attn$ th train.lua -data_file data/demo-train.hdf5 -val_data_file data/demo-val.hdf5 -savefile demo-model
loading data...	
done!	
Source vocab size: 28721, Target vocab size: 42787	
Source max sent len: 50, Target max sent len: 52	
/usr/local/bin/luajit: stack overflow
stack traceback:
	[C]: at 0x7f29cf7fb9d0
	[C]: at 0x7f29cf7fb9d0
	[C]: in function '__index'
	train.lua:493: in function 'callback'
	/usr/local/share/lua/5.1/nn/Module.lua:318: in function 'apply'
	train.lua:503: in function 'callback'
	/usr/local/share/lua/5.1/nn/Module.lua:318: in function 'apply'
	train.lua:503: in function 'callback'
	/usr/local/share/lua/5.1/nn/Module.lua:318: in function 'apply'
	train.lua:503: in function 'callback'
	/usr/local/share/lua/5.1/nn/Module.lua:318: in function 'apply'
	...
	/usr/local/share/lua/5.1/nn/Module.lua:318: in function 'apply'
	train.lua:503: in function 'callback'
	/usr/local/share/lua/5.1/nn/Module.lua:318: in function 'apply'
	train.lua:503: in function 'callback'
	/usr/local/share/lua/5.1/nn/Module.lua:318: in function 'apply'
	train.lua:578: in function 'main'
	train.lua:584: in main chunk
	[C]: in function 'dofile'
	/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406260
ubuntu@ip-xxxx:/mnt/seq2seq-attn$ luajit -v
LuaJIT 2.0.4 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/

 _____              _     
|_   _|            | |    
  | | ___  _ __ ___| |__  
  | |/ _ \| '__/ __| '_ \ 
  | | (_) | | | (__| | | |
  \_/\___/|_|  \___|_| |_|

**Comment by yoonkim** [comment]
thanks! i just pushed a fix for it.

**Comment by shuguangwang** [comment]
cool. I see training is ongoing. But is it expected to take a while to train on demo data? It has been 20mins now. Is it expected?

**Comment by yoonkim** [comment]
Training on CPU should be very slow (in fact too slow to be practical for anything other than toy problems...). Highly recommend using GPU.

**Comment by srush** [comment]
To follow-up. You have to explicitly say -gpuid 1 to train with GPU (we will make that more clear.)

**Comment by shuguangwang** [comment]
I got training working, but now beam search returns empty pred text for all input. Did I miss some other options?

Here is the command i used to trained the model. It took like 40 mins to train the model.
> th train.lua -gpuid 1 -cudnn 0 -data_file data/demo-train.hdf5 -val_data_file data/demo-val.hdf5 -savefile demo-model

Here is the command to get pred txt:

> th beam.lua -src_file data/src-val.txt -output_file pred.txt -src_dict data/demo.src.dict -targ_dict data/demo.targ.dict -model demo-model_final.t7

**Comment by srush** [comment]
What does beam.lua print out to the command-line?

**Comment by shuguangwang** [comment]
standout is also empty.

**Comment by yoonkim** [comment]
so it doesn't even print things like "loading model.t7..."?

**Comment by shuguangwang** [comment]
Here is what I see:

ubuntu@ip-xxxx:/mnt/seq2seq-attn$ th beam.lua -src_file data/src-val.txt -output_file pred.txt -src_dict data/demo.src.dict -targ_dict data/demo.targ.dict -model demo-model_final.t7
loading demo-model_final.t7...	
done!	
SENT 1: Parliament Does Not Support Amendment Freeing Tymoshenko	
PRED 1: 	
	
SENT 2: Today , the Ukraine parliament dismissed , within the Code of Criminal Procedure amendment , the motion to revoke an article based on which the opposition leader , Yulia Tymoshenko , was sentenced .	
PRED 2: 	
	
SENT 3: The amendment that would lead to freeing the imprisoned former Prime Minister was revoked during second reading of the proposal for mitigation of sentences for economic offences .	
PRED 3: 	
	
SENT 4: In October , Tymoshenko was sentenced to seven years in prison for entering into what was reported to be a disadvantageous gas deal with Russia .	
PRED 4: 	
	
SENT 5: The verdict is not yet final; the court will hear Tymoshenko &apos;s appeal in December .	
PRED 5: 	
	
SENT 6: Tymoshenko claims the verdict is a political revenge of the regime; in the West , the trial has also evoked suspicion of being biased .	
PRED 6: 	
	
SENT 7: The proposal to remove Article 365 from the Code of Criminal Procedure , upon which the former Prime Minister was sentenced , was supported by 147 members of parliament .	
PRED 7: 	
	
SENT 8: Its ratification would require 226 votes .	
PRED 8: 	
	
....

the rest of 3000 results

**Comment by yoonkim** [comment]
Did you train for all epochs?
I just tried running the tutorial and it produced non-empty predictions. Here are my outputs

-------------------------------------------
loading seq2seq_lstm_attn_final.t7...
done!
SENT 1: Parliament Does Not Support Amendment Freeing Tymoshenko
PRED 1: Leider ist es in diesem Fall .

SENT 2: Today , the Ukraine parliament dismissed , within the Code of Criminal Procedure amendment , the motion to revoke an article based on which the opposition leader , Yulia Tymoshenko , was sentenced 
.
PRED 2: Die Zeit , die in der Lage , die in der Lage , die in der Lage , die in der Lage , die in der Lage , die in der Lage in der Lage .

SENT 3: The amendment that would lead to freeing the imprisoned former Prime Minister was revoked during second reading of the proposal for mitigation of sentences for economic offences .
PRED 3: Die Tatsache , dass die Europäische Union in den Mitgliedstaaten in Bezug auf die Förderung des Europäischen Parlaments ist , so dass es sich in den Mitgliedstaaten in diesem Fall stellen .

SENT 4: In October , Tymoshenko was sentenced to seven years in prison for entering into what was reported to be a disadvantageous gas deal with Russia .
PRED 4: In den letzten zehn Jahren wurde er in den letzten zehn Jahren in den letzten zehn Jahren in der Welt .

SENT 5: The verdict is not yet final; the court will hear Tymoshenko &apos;s appeal in December .
PRED 5: Die EU ist nicht nur nicht nur auf die Lage , die in der Lage ist .

SENT 6: Tymoshenko claims the verdict is a political revenge of the regime; in the West , the trial has also evoked suspicion of being biased .
PRED 6: In der Nähe des Hotels ist es in der Region , die in der Lage , die in der Lage in der Nähe der Welt in der Welt in der Ukraine .

SENT 7: The proposal to remove Article 365 from the Code of Criminal Procedure , upon which the former Prime Minister was sentenced , was supported by 147 members of parliament .
PRED 7: Die Tatsache , dass die Europäische Union in den Mitgliedstaaten in den Mitgliedstaaten in den Mitgliedstaaten in den Mitgliedstaaten in den Mitgliedstaaten in den Mitgliedstaaten in der EU in der 
EU in der EU ist .

SENT 8: Its ratification would require 226 votes .
PRED 8: Die Sitzung würde nicht .

SENT 9: Libya &apos;s Victory
PRED 9: Abstimmungsstunde

SENT 10: The story of Libya &apos;s liberation , or rebellion , already has its defeated .
PRED 10: Die Firma , die sich in der Lage ist .

SENT 11: Muammar Kaddafi is buried at an unknown place in the desert . Without him , the war is over .
PRED 11: In der Region ist es in der Region , die in der Lage in der Nähe der Welt in der Schweiz zu erreichen .

SENT 12: It is time to define the winners .
PRED 12: Es ist wichtig , dass die EU in der Ukraine ist .

SENT 13: As a rule , Islamists win in the country; the question is whether they are the moderate or the radical ones .
PRED 13: Wie in den letzten zehn Jahren ist es auch eine Reihe von solchen Millionen Euro .

SENT 14: The transitional cabinet declared itself a follower of the customary Sharia law , of which we have already heard .
PRED 14: Die Firma , die in der Lage , die wir in der Lage in der Lage ist .

**Comment by shuguangwang** [comment]
Mind sharing the actual command you train the model?

**Comment by shuguangwang** [comment]
I dont see "lstm_attn_final" in my model name, is it just the name you gave model?And my command was exactly this:
> th train.lua -gpuid 1 -data_file data/demo-train.hdf5 -val_data_file data/demo-val.hdf5 -savefile demo-model

**Comment by yoonkim** [comment]
Yeah the model name is because of your commandline -savefile demo-model, but this shouldn't change things. Would you mind trying running beam search with one of the pre-trained models? 

https://drive.google.com/open?id=0BzhmYioWLRn_aEVnd0ZNcWd0Y2c

**Comment by shuguangwang** [comment]
I still need to get training ok so I can move on to a new data set. Mind also share the preprocessed input data as well? i.e., those dicts and hdf5 files.

**Comment by shuguangwang** [comment]
Finally downloaded the model but it gives another error:

> ubuntu@ip-xxxx:/mnt/seq2seq-attn$ th beam.lua -src_file data/src-val.txt -output_file pred.txt -src_dict train_models/en.dict -targ_dict train_models/de.dict -model trained_models/en-to-de-model.t7 
loading trained_models/en-to-de-model.t7...	
done!	
/usr/local/bin/luajit: beam.lua:312: attempt to index local 'f' (a nil value)
stack traceback:
	beam.lua:312: in function 'idx2key'
	beam.lua:466: in function 'main'
	beam.lua:593: in main chunk
	[C]: in function 'dofile'
	/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406260

**Comment by srush** [comment]
It looks like it can't find one of the dictionary files. Are you sure those are both present?

**Comment by yoonkim** [comment]
i think the paths should be trained_models/de.dict and trained_models/en.dict (not train_models/)

**Comment by shuguangwang** [comment]
right, using trained model it worked. so the issue is that model was not trained properly

**Comment by yoonkim** [comment]
Right. Would you mind printing out the logs from training? Thanks!

**Comment by shuguangwang** [comment]
here is the log:

using CUDA on GPU 1...	
loading cudnn...	
loading data...	
done!	
Source vocab size: 28721, Target vocab size: 42787	
Source max sent len: 50, Target max sent len: 52	
Number of parameters: 66948287	
Train	29438435801.257	
Valid	2710481.7411732	
{
  1 : 2710481.7411732
}
saving checkpoint to demo-model_epoch1.00_2710481.74.t7	
Train	18413475546.003	
Valid	8855627329734.2	
{
  1 : 2710481.7411732
  2 : 8855627329734.2
}
saving checkpoint to demo-model_epoch2.00_8855627329734.16.t7	
Train	49657158.118976	
Valid	24417916.59578	
{
  1 : 2710481.7411732
  2 : 8855627329734.2
  3 : 24417916.59578
}
saving checkpoint to demo-model_epoch3.00_24417916.60.t7	
Train	1637233.6989064	
Valid	1078674.2170225	
{
  1 : 2710481.7411732
  2 : 8855627329734.2
  3 : 24417916.59578
  4 : 1078674.2170225
}
saving checkpoint to demo-model_epoch4.00_1078674.22.t7	
Train	443303.88099115	
Valid	24081.43764027	
{
  1 : 2710481.7411732
  2 : 8855627329734.2
  3 : 24417916.59578
  4 : 1078674.2170225
  5 : 24081.43764027
}
saving checkpoint to demo-model_epoch5.00_24081.44.t7	
Train	244283.01333182	
Valid	26054.958632744	
{
  1 : 2710481.7411732
  2 : 8855627329734.2
  3 : 24417916.59578
  4 : 1078674.2170225
  5 : 24081.43764027
  6 : 26054.958632744
}
saving checkpoint to demo-model_epoch6.00_26054.96.t7	

Train	190364.22274661	
Valid	21844.009174936	
{
  1 : 2710481.7411732
  2 : 8855627329734.2
  3 : 24417916.59578
  4 : 1078674.2170225
  5 : 24081.43764027
  6 : 26054.958632744
  7 : 21844.009174936
}
saving checkpoint to demo-model_epoch7.00_21844.01.t7	
Train	176694.12910244	
Valid	21224.023847009	
{
  1 : 2710481.7411732
  2 : 8855627329734.2
  3 : 24417916.59578
  4 : 1078674.2170225
  5 : 24081.43764027
  6 : 26054.958632744
  7 : 21844.009174936
  8 : 21224.023847009
}
saving checkpoint to demo-model_epoch8.00_21224.02.t7	
Train	170404.25408523	
Valid	20721.661916173	
{
  1 : 2710481.7411732
  2 : 8855627329734.2
  3 : 24417916.59578
  4 : 1078674.2170225
  5 : 24081.43764027
  6 : 26054.958632744
  7 : 21844.009174936
  8 : 21224.023847009
  9 : 20721.661916173
}
saving checkpoint to demo-model_epoch9.00_20721.66.t7	
Train	166362.29284903	
Valid	20709.405886529	
{
  1 : 2710481.7411732
  2 : 8855627329734.2
  3 : 24417916.59578
  4 : 1078674.2170225
  5 : 24081.43764027
  6 : 26054.958632744
  7 : 21844.009174936
  8 : 21224.023847009
  9 : 20721.661916173
  10 : 20709.405886529
}
saving checkpoint to demo-model_epoch10.00_20709.41.t7	
Train	164398.10528936	
Valid	20747.246129641	
{
  1 : 2710481.7411732
  2 : 8855627329734.2
  3 : 24417916.59578
  4 : 1078674.2170225
  5 : 24081.43764027
  6 : 26054.958632744
  7 : 21844.009174936
  8 : 21224.023847009
  9 : 20721.661916173
  10 : 20709.405886529
  11 : 20747.246129641
}
saving checkpoint to demo-model_epoch11.00_20747.25.t7	
Train	166268.99933259	
Valid	20724.242746044	
{
  1 : 2710481.7411732
  2 : 8855627329734.2
  3 : 24417916.59578
  4 : 1078674.2170225
  5 : 24081.43764027
  6 : 26054.958632744
  7 : 21844.009174936
  8 : 21224.023847009
  9 : 20721.661916173
  10 : 20709.405886529
  11 : 20747.246129641
  12 : 20724.242746044
}
saving checkpoint to demo-model_epoch12.00_20724.24.t7	
Train	163374.89881939	
Valid	20767.251777174	
{
  1 : 2710481.7411732
  2 : 8855627329734.2
  3 : 24417916.59578
  4 : 1078674.2170225
  5 : 24081.43764027
  6 : 26054.958632744
  7 : 21844.009174936
  8 : 21224.023847009
  9 : 20721.661916173
  10 : 20709.405886529
  11 : 20747.246129641
  12 : 20724.242746044
  13 : 20767.251777174
}
saving checkpoint to demo-model_epoch13.00_20767.25.t7	
saving final model to demo-model_final.t7

**Comment by yoonkim** [comment]
Interesting, here is what my log looks like. Can you try updating to the latest version of the repo?
Seems like you might be using a previous version where I was testing a bunch of things.

using CUDA on GPU 3...
loading cudnn...
loading data...
done!
Source vocab size: 28721, Target vocab size: 42787
Source max sent len: 50, Target max sent len: 52
Number of parameters: 66948287
Train   20738.303960954
Valid   3266.4936257744
{
  1 : 3266.4936257744
}
saving checkpoint to seq2seq_lstm_attn_epoch1.00_3266.49.t7
Train   2041.0467959909
Valid   1710.0632072274
{
  1 : 3266.4936257744
  2 : 1710.0632072274
}
saving checkpoint to seq2seq_lstm_attn_epoch2.00_1710.06.t7
Train   1218.8937050787
Valid   1301.3012089853
{
  1 : 3266.4936257744
  2 : 1710.0632072274
  3 : 1301.3012089853
}
saving checkpoint to seq2seq_lstm_attn_epoch3.00_1301.30.t7
Train   866.06919377648
Valid   1191.3694813256
{
  1 : 3266.4936257744
  2 : 1710.0632072274
  3 : 1301.3012089853
  4 : 1191.3694813256
}
saving checkpoint to seq2seq_lstm_attn_epoch4.00_1191.37.t7
Train   679.84656300289
Valid   1073.8252991633
{
  1 : 3266.4936257744
  2 : 1710.0632072274
  3 : 1301.3012089853
  4 : 1191.3694813256
  5 : 1073.8252991633
}

**Comment by shuguangwang** [comment]
I am already using the latest version of the repo. retraining... and this is what I see now.

using CUDA on GPU 1...	
loading cudnn...	
loading data...	
done!	
Source vocab size: 28721, Target vocab size: 42787	
Source max sent len: 50, Target max sent len: 52	
Number of parameters: 66948287	
Train	99811387330.431	
Valid	3535331.75593	
{
  1 : 3535331.75593
}
saving checkpoint to demo-model_epoch1.00_3535331.76.t7	
Train	44851698634.07	
Valid	330515753.63983	
{
  1 : 3535331.75593
  2 : 330515753.63983
}
saving checkpoint to demo-model_epoch2.00_330515753.64.t7	
Train	44508842.145637	
Valid	2918376.651469	
{
  1 : 3535331.75593
  2 : 330515753.63983
  3 : 2918376.651469
}

**Comment by yoonkim** [comment]
Interesting, when I upgrade to the latest torch my model also fails to train... let me look into this a bit further.

**Comment by shuguangwang** [comment]
Just for your information, the model does not seem to converge even when I specified 50 epochs.

**Comment by yoonkim** [comment]
Hi, I've tracked down the issue and it seems like in the latest version of 'nn', ClassNLLCriterion() fails to average the losses/gradients when one of the weights is zero. More detail is here: https://github.com/torch/nn/issues/775

I've updated the repo with a work-around (by manually averaging the gradients).

Here are my numbers--can you see if you are able to obtain similar results?

using CUDA on GPU 2...
loading cudnn...
loading data...
done!
Source vocab size: 28721, Target vocab size: 42787
Source max sent len: 50, Target max sent len: 52
Number of parameters: 66948287
Epoch: 1, Batch: 50/184, Batch size: 43, LR: 1.0000, PPL: 350468.10, |Param|: 473.18, |GParam|: 154.17, Training: 7063/2589/4474 total/source/target tokens/sec
Epoch: 1, Batch: 100/184, Batch size: 64, LR: 1.0000, PPL: 376431.15, |Param|: 473.78, |GParam|: 110.38, Training: 7493/2670/4823 total/source/target tokens/sec
Epoch: 1, Batch: 150/184, Batch size: 64, LR: 1.0000, PPL: 114794.29, |Param|: 474.48, |GParam|: 14.26, Training: 7202/2634/4568 total/source/target tokens/sec
Train   64778.109572103
Valid   3215.1384400163
{
  1 : 3215.1384400163
}
saving checkpoint to seq2seq_lstm_attn_epoch1.00_3215.14.t7
Epoch: 2, Batch: 50/184, Batch size: 64, LR: 1.0000, PPL: 2672.24, |Param|: 475.76, |GParam|: 2.93, Training: 7434/2639/4794 total/source/target tokens/sec
Epoch: 2, Batch: 100/184, Batch size: 64, LR: 1.0000, PPL: 2464.84, |Param|: 476.59, |GParam|: 4.89, Training: 7351/2653/4698 total/source/target tokens/sec
Epoch: 2, Batch: 150/184, Batch size: 7, LR: 1.0000, PPL: 2252.44, |Param|: 477.45, |GParam|: 7.26, Training: 7356/2684/4672 total/source/target tokens/sec
Train   2199.1005795379
Valid   1890.6905344821
{
  1 : 3215.1384400163
  2 : 1890.6905344821
}
saving checkpoint to seq2seq_lstm_attn_epoch2.00_1890.69.t7
Epoch: 3, Batch: 50/184, Batch size: 37, LR: 1.0000, PPL: 1596.45, |Param|: 478.97, |GParam|: 5.72, Training: 7592/2850/4742 total/source/target tokens/sec
Epoch: 3, Batch: 100/184, Batch size: 58, LR: 1.0000, PPL: 1432.65, |Param|: 479.85, |GParam|: 8.46, Training: 7553/2770/4782 total/source/target tokens/sec
Epoch: 3, Batch: 150/184, Batch size: 3, LR: 1.0000, PPL: 1379.97, |Param|: 480.75, |GParam|: 14.32, Training: 7604/2787/4816 total/source/target tokens/sec
Train   1341.5249072298
Valid   1793.0411778955
{
  1 : 3215.1384400163
  2 : 1890.6905344821
  3 : 1793.0411778955
}
saving checkpoint to seq2seq_lstm_attn_epoch3.00_1793.04.t7

**Comment by shuguangwang** [comment]
Thanks for the update. I see different training log and decoding is not work still yet (still empty pred).

Since the input is the same, should I see exactly the same training log?

using CUDA on GPU 1...	
loading cudnn...	
loading data...	
done!	
Source vocab size: 28721, Target vocab size: 42787	
Source max sent len: 50, Target max sent len: 52	
Number of parameters: 66948287	
Epoch: 1, Batch: 50/184, Batch size: 43, LR: 1.0000, PPL: 551545.93, |Param|: 486.91, |GParam|: 1042.32, Training: 3075/1127/1948 total/source/target tokens/sec	
Epoch: 1, Batch: 100/184, Batch size: 64, LR: 1.0000, PPL: 452771.07, |Param|: 524.92, |GParam|: 239.69, Training: 3128/1114/2013 total/source/target tokens/sec	
Epoch: 1, Batch: 150/184, Batch size: 64, LR: 1.0000, PPL: 623284.34, |Param|: 549.12, |GParam|: 2464559820232687.50, Training: 3028/1107/1920 total/source/target tokens/sec	
Train	634282.03269856	
Valid	1417740.9509971	
{
  1 : 1417740.9509971
}
saving checkpoint to demo-model_epoch1.00_1417740.95.t7	
Epoch: 2, Batch: 50/184, Batch size: 64, LR: 1.0000, PPL: 1379868.97, |Param|: 614.02, |GParam|: 263.35, Training: 3046/1081/1964 total/source/target tokens/sec	
Epoch: 2, Batch: 100/184, Batch size: 64, LR: 1.0000, PPL: 1307734.70, |Param|: 700.22, |GParam|: 364.98, Training: 3050/1100/1949 total/source/target tokens/sec	
Epoch: 2, Batch: 150/184, Batch size: 7, LR: 1.0000, PPL: 1236387.82, |Param|: 812.44, |GParam|: 343.23, Training: 3051/1113/1938 total/source/target tokens/sec	
Train	1418993.1595324	
Valid	165144.64875152	
{
  1 : 1417740.9509971
  2 : 165144.64875152
}
saving checkpoint to demo-model_epoch2.00_165144.65.t7	
Epoch: 3, Batch: 50/184, Batch size: 37, LR: 1.0000, PPL: 1222748.66, |Param|: 1033.96, |GParam|: 106.59, Training: 3024/1135/1889 total/source/target tokens/sec	
Epoch: 3, Batch: 100/184, Batch size: 58, LR: 1.0000, PPL: 1463235.67, |Param|: 1176.96, |GParam|: 300.41, Training: 3072/1127/1945 total/source/target tokens/sec	
Epoch: 3, Batch: 150/184, Batch size: 3, LR: 1.0000, PPL: 1457843.43, |Param|: 1323.62, |GParam|: 328.78, Training: 3082/1130/1952 total/source/target tokens/sec	
Train	1548203.5903404	
Valid	1163834.7693276	
{
  1 : 1417740.9509971
  2 : 165144.64875152
  3 : 1163834.7693276
}
saving checkpoint to demo-model_epoch3.00_1163834.77.t7

**Comment by shuguangwang** [comment]
these are packages installed luarocks: 

Installed rocks:
----------------

cudnn
   scm-1 (installed) - /usr/local/lib/luarocks/rocks

cunn
   scm-1 (installed) - /usr/local/lib/luarocks/rocks

cutorch
   scm-1 (installed) - /usr/local/lib/luarocks/rocks

cwrap
   scm-1 (installed) - /usr/local/lib/luarocks/rocks

dok
   scm-1 (installed) - /usr/local/lib/luarocks/rocks

dpnn
   scm-1 (installed) - /usr/local/lib/luarocks/rocks

findcuda
   scm-1 (installed) - /usr/local/lib/luarocks/rocks

fn
   0-0 (installed) - /usr/local/lib/luarocks/rocks

gnuplot
   scm-1 (installed) - /usr/local/lib/luarocks/rocks

graph
   scm-1 (installed) - /usr/local/lib/luarocks/rocks

hdf5
   20-0 (installed) - /usr/local/lib/luarocks/rocks

image
   1.1.alpha-0 (installed) - /usr/local/lib/luarocks/rocks

logroll
   0-0 (installed) - /usr/local/lib/luarocks/rocks

lua-cjson
   2.1.0-1 (installed) - /usr/local/lib/luarocks/rocks

luaffi
   scm-1 (installed) - /usr/local/lib/luarocks/rocks

luafilesystem
   1.6.3-2 (installed) - /usr/local/lib/luarocks/rocks

luautf8
   0.1.1-1 (installed) - /usr/local/lib/luarocks/rocks

moses
   1.4.0-1 (installed) - /usr/local/lib/luarocks/rocks

nn
   scm-1 (installed) - /usr/local/lib/luarocks/rocks

nngraph
   scm-1 (installed) - /usr/local/lib/luarocks/rocks

nnx
   0.1-1 (installed) - /usr/local/lib/luarocks/rocks

optim
   1.0.5-0 (installed) - /usr/local/lib/luarocks/rocks

paths
   scm-1 (installed) - /usr/local/lib/luarocks/rocks

penlight
   1.3.2-2 (installed) - /usr/local/lib/luarocks/rocks

pprint
   0-0 (installed) - /usr/local/lib/luarocks/rocks

qtlua
   scm-1 (installed) - /usr/local/lib/luarocks/rocks

qttorch
   scm-1 (installed) - /usr/local/lib/luarocks/rocks

rnn
   scm-1 (installed) - /usr/local/lib/luarocks/rocks

sundown
   scm-1 (installed) - /usr/local/lib/luarocks/rocks

sys
   1.1-0 (installed) - /usr/local/lib/luarocks/rocks

torch
   scm-1 (installed) - /usr/local/lib/luarocks/rocks

torchx
   scm-1 (installed) - /usr/local/lib/luarocks/rocks

totem
   0-0 (installed) - /usr/local/lib/luarocks/rocks

trepl
   scm-1 (installed) - /usr/local/lib/luarocks/rocks

util
   0-0 (installed) - /usr/local/lib/luarocks/rocks

xlua
   1.1-0 (installed) - /usr/local/lib/luarocks/rocks

**Comment by yoonkim** [comment]
hmm not sure why it's still not working...

can you try:
- updating nn, cunn, torch to the latest
- see what the outputs are (loss1 and loss2) when you run this code?

**Comment by shuguangwang** [comment]
I should have latest torch, nn, and cunn. anyway I updated them again.

the code gives loss1 = -0.5 and loss2 = -0.25

**Comment by yoonkim** [comment]
Ok, one more thing if you dont' mind (want to see if a CPU/GPU issue):

can you try running on the cpu and then printing out log for a few iterations:

th train.lua -gpuid -1 print_every 1 -rnn_size 50 -num_layers 1

Here is my output, and since we are using the same seed we should see the exact same numbers. (I get the same numbers on both old/new versions of torch on diff computers).

Source vocab size: 28721, Target vocab size: 42787	
Source max sent len: 50, Target max sent len: 52	
Number of parameters: 38174037	
Epoch: 1, Batch: 1/184, Batch size: 64, LR: 1.0000, PPL: 43213.62, |Param|: 356.69, |GParam|: 1.85, Training: 726/201/524 total/source/target tokens/sec	
Epoch: 1, Batch: 2/184, Batch size: 64, LR: 1.0000, PPL: 39585.89, |Param|: 356.70, |GParam|: 1.51, Training: 661/160/501 total/source/target tokens/sec	
Epoch: 1, Batch: 3/184, Batch size: 64, LR: 1.0000, PPL: 36046.98, |Param|: 356.76, |GParam|: 4.70, Training: 799/288/511 total/source/target tokens/sec	
Epoch: 1, Batch: 4/184, Batch size: 64, LR: 1.0000, PPL: 29223.90, |Param|: 356.86, |GParam|: 7.71, Training: 754/280/474 total/source/target tokens/sec	
Epoch: 1, Batch: 5/184, Batch size: 64, LR: 1.0000, PPL: 50397.54, |Param|: 356.91, |GParam|: 206.96, Training: 770/285/484 total/source/target tokens/sec

**Comment by shuguangwang** [comment]
here is what i got with cpu mode:

> ubuntu@ip-xxxx:/mnt/seq2seq-attn$ th train.lua -data_file data/demo-train.hdf5 -val_data_file data/demo-val.hdf5 -savefile demo-model -gpuid -1 -epochs 2 -rnn_size 50 -num_layers 1 -print_every 1
loading data...	
done!	
Source vocab size: 28721, Target vocab size: 42787	
Source max sent len: 50, Target max sent len: 52	
Number of parameters: 38174037	
Epoch: 1, Batch: 1/184, Batch size: 64, LR: 1.0000, PPL: 43213.62, |Param|: 356.69, |GParam|: 1.85, Training: 616/171/445 total/source/target tokens/sec	
Epoch: 1, Batch: 2/184, Batch size: 64, LR: 1.0000, PPL: 39585.89, |Param|: 356.70, |GParam|: 1.51, Training: 597/144/452 total/source/target tokens/sec	
Epoch: 1, Batch: 3/184, Batch size: 64, LR: 1.0000, PPL: 36046.98, |Param|: 356.76, |GParam|: 4.70, Training: 695/250/444 total/source/target tokens/sec	
Epoch: 1, Batch: 4/184, Batch size: 64, LR: 1.0000, PPL: 29223.90, |Param|: 356.86, |GParam|: 7.71, Training: 686/255/431 total/source/target tokens/sec	
Epoch: 1, Batch: 5/184, Batch size: 64, LR: 1.0000, PPL: 50397.54, |Param|: 356.91, |GParam|: 206.96, Training: 685/254/431 total/source/target tokens/sec

**Comment by yoonkim** [comment]
that's really strange that our CPU numbers match exactly but GPU numbers are way off... FYI here are my numbers on the GPU 

using CUDA on GPU 2...
loading cudnn...
loading data...
done!
Source vocab size: 28721, Target vocab size: 42787
Source max sent len: 50, Target max sent len: 52
Number of parameters: 38174037
Epoch: 1, Batch: 1/184, Batch size: 29, LR: 1.0000, PPL: 43004.33, |Param|: 356.76, |GParam|: 3.42, Training: 7077/2964/4112 total/source/target tokens/sec
Epoch: 1, Batch: 2/184, Batch size: 64, LR: 1.0000, PPL: 36151.37, |Param|: 356.78, |GParam|: 1.99, Training: 8476/3228/5248 total/source/target tokens/sec
Epoch: 1, Batch: 3/184, Batch size: 1, LR: 1.0000, PPL: 35720.50, |Param|: 356.85, |GParam|: 13.81, Training: 6160/2358/3802 total/source/target tokens/sec
Epoch: 1, Batch: 4/184, Batch size: 64, LR: 1.0000, PPL: 29682.95, |Param|: 356.84, |GParam|: 74.53, Training: 8217/3164/5053 total/source/target tokens/sec
Epoch: 1, Batch: 5/184, Batch size: 64, LR: 1.0000, PPL: 27479.81, |Param|: 356.91, |GParam|: 4.49, Training: 10133/3817/6316 total/source/target tokens/sec
Epoch: 1, Batch: 6/184, Batch size: 64, LR: 1.0000, PPL: 21694.98, |Param|: 357.01, |GParam|: 9.79, Training: 11251/4373/6878 total/source/target tokens/sec
Epoch: 1, Batch: 7/184, Batch size: 27, LR: 1.0000, PPL: 27495.69, |Param|: 357.00, |GParam|: 168.07, Training: 11036/4365/6671 total/source/target tokens/sec
Epoch: 1, Batch: 8/184, Batch size: 64, LR: 1.0000, PPL: 27237.45, |Param|: 356.96, |GParam|: 40.79, Training: 11831/4698/7132 total/source/target tokens/sec

**Comment by shuguangwang** [comment]
what are your torch, cudnn versions? i am on dev version on my of the packages and you can check it in my previous post.

**Comment by shuguangwang** [comment]
ubuntu@ip-10-64-10-86:~/seq2seq-attn$ th train.lua -data_file data/demo-train.hdf5 -val_data_file data/demo-val.hdf5 -savefile demo-model -gpuid 1 -print_every 1 -rnn_size 50 -num_layers 1 
using CUDA on GPU 1...	
loading cudnn...	
loading data...	
done!	
Source vocab size: 28721, Target vocab size: 42787	
Source max sent len: 50, Target max sent len: 52	
Number of parameters: 38174037	
Epoch: 1, Batch: 1/184, Batch size: 29, LR: 1.0000, PPL: 43004.33, |Param|: 356.76, |GParam|: 3.42, Training: 4217/1766/2450 total/source/target tokens/sec	
Epoch: 1, Batch: 2/184, Batch size: 64, LR: 1.0000, PPL: 36151.46, |Param|: 356.78, |GParam|: 1.99, Training: 5700/2170/3529 total/source/target tokens/sec	
Epoch: 1, Batch: 3/184, Batch size: 1, LR: 1.0000, PPL: 35720.83, |Param|: 356.85, |GParam|: 13.72, Training: 4114/1574/2539 total/source/target tokens/sec	
Epoch: 1, Batch: 4/184, Batch size: 64, LR: 1.0000, PPL: 29259.37, |Param|: 356.86, |GParam|: 63.36, Training: 5570/2145/3425 total/source/target tokens/sec	
Epoch: 1, Batch: 5/184, Batch size: 64, LR: 1.0000, PPL: 27434.44, |Param|: 356.90, |GParam|: 10.93, Training: 6458/2432/4025 total/source/target tokens/sec	
Epoch: 1, Batch: 6/184, Batch size: 64, LR: 1.0000, PPL: 25302.77, |Param|: 356.96, |GParam|: 138.75, Training: 7155/2781/4374 total/source/target tokens/sec	
Epoch: 1, Batch: 7/184, Batch size: 27, LR: 1.0000, PPL: 23208.36, |Param|: 356.95, |GParam|: 52.66, Training: 6884/2723/4161 total/source/target tokens/sec	
Epoch: 1, Batch: 8/184, Batch size: 64, LR: 1.0000, PPL: 20969.77, |Param|: 356.99, |GParam|: 50.68, Training: 7237/2874/4363 total/source/target tokens/sec	
Epoch: 1, Batch: 9/184, Batch size: 64, LR: 1.0000, PPL: 19945.48, |Param|: 357.05, |GParam|: 23.21, Training: 7376/2826/4549 total/source/target tokens/sec	
Epoch: 1, Batch: 10/184, Batch size: 64, LR: 1.0000, PPL: 19259.41, |Param|: 357.10, |GParam|: 37.57, Training: 7613/2832/4781 total/source/target tokens/sec	
Epoch: 1, Batch: 11/184, Batch size: 12, LR: 1.0000, PPL: 19246.40, |Param|: 357.15, |GParam|: 8023317.72, Training: 7341/2743/4598 total/source/target tokens/sec	
Epoch: 1, Batch: 12/184, Batch size: 64, LR: 1.0000, PPL: 17828.07, |Param|: 357.23, |GParam|: 58.06, Training: 7623/2868/4755 total/source/target tokens/sec	
Epoch: 1, Batch: 13/184, Batch size: 64, LR: 1.0000, PPL: 18007.85, |Param|: 357.31, |GParam|: 167.03, Training: 7921/3087/4834 total/source/target tokens/sec	
Epoch: 1, Batch: 14/184, Batch size: 64, LR: 1.0000, PPL: 20023.58, |Param|: 357.36, |GParam|: 26769532681187.36, Training: 8177/3232/4945 total/source/target tokens/sec	
Epoch: 1, Batch: 15/184, Batch size: 64, LR: 1.0000, PPL: 21100.18, |Param|: 357.49, |GParam|: 2020.06, Training: 8446/3400/5045 total/source/target tokens/sec	
Epoch: 1, Batch: 16/184, Batch size: 64, LR: 1.0000, PPL: 22784.20, |Param|: 357.64, |GParam|: 126.39, Training: 8514/3423/5090 total/source/target tokens/sec	
Epoch: 1, Batch: 17/184, Batch size: 64, LR: 1.0000, PPL: 24239.97, |Param|: 357.77, |GParam|: 125.63, Training: 8545/3412/5132 total/source/target tokens/sec	
Epoch: 1, Batch: 18/184, Batch size: 28, LR: 1.0000, PPL: 26261.11, |Param|: 357.80, |GParam|: 209758190.84, Training: 8370/3376/4994 total/source/target tokens/sec	
Epoch: 1, Batch: 19/184, Batch size: 64, LR: 1.0000, PPL: 28569.11, |Param|: 357.75, |GParam|: 4843584.43, Training: 8408/3351/5057 total/source/target tokens/sec	
Epoch: 1, Batch: 20/184, Batch size: 64, LR: 1.0000, PPL: 29752.08, |Param|: 357.72, |GParam|: 16663.51, Training: 8416/3318/5098 total/source/target tokens/sec	
Epoch: 1, Batch: 21/184, Batch size: 64, LR: 1.0000, PPL: 30715.91, |Param|: 357.78, |GParam|: 710.69, Training: 8470/3304/5165 total/source/target tokens/sec	
Epoch: 1, Batch: 22/184, Batch size: 64, LR: 1.0000, PPL: 32065.45, |Param|: 357.87, |GParam|: 231.47, Training: 8557/3346/5210 total/source/target tokens/sec

**Comment by yoonkim** [comment]
Hi, it does seem to be a cuda 7.5 issue. My gradients also blow up with 7.5. I'll update the readme to note that the model should be used with cuda 6.5

Epoch: 1, Batch: 1/184, Batch size: 29, LR: 1.0000, PPL: 43004.33, |Param|: 356.76, |GParam|: 3.42, Training: 6919/2898/4020 total/source/target tokens/sec
Epoch: 1, Batch: 2/184, Batch size: 64, LR: 1.0000, PPL: 36151.46, |Param|: 356.78, |GParam|: 1.99, Training: 8396/3197/5198 total/source/target tokens/sec
Epoch: 1, Batch: 3/184, Batch size: 1, LR: 1.0000, PPL: 35720.83, |Param|: 356.85, |GParam|: 13.72, Training: 6087/2329/3757 total/source/target tokens/sec
Epoch: 1, Batch: 4/184, Batch size: 64, LR: 1.0000, PPL: 29259.37, |Param|: 356.86, |GParam|: 63.36, Training: 8197/3156/5040 total/source/target tokens/sec
Epoch: 1, Batch: 5/184, Batch size: 64, LR: 1.0000, PPL: 27434.44, |Param|: 356.90, |GParam|: 10.93, Training: 10087/3799/6287 total/source/target tokens/sec
Epoch: 1, Batch: 6/184, Batch size: 64, LR: 1.0000, PPL: 25302.77, |Param|: 356.96, |GParam|: 138.75, Training: 11196/4351/6844 total/source/target tokens/sec
Epoch: 1, Batch: 7/184, Batch size: 27, LR: 1.0000, PPL: 23208.36, |Param|: 356.95, |GParam|: 52.66, Training: 10991/4347/6644 total/source/target tokens/sec
Epoch: 1, Batch: 8/184, Batch size: 64, LR: 1.0000, PPL: 20969.77, |Param|: 356.99, |GParam|: 50.68, Training: 11791/4682/7109 total/source/target tokens/sec
Epoch: 1, Batch: 9/184, Batch size: 64, LR: 1.0000, PPL: 19945.48, |Param|: 357.05, |GParam|: 23.21, Training: 12229/4685/7543 total/source/target tokens/sec
Epoch: 1, Batch: 10/184, Batch size: 64, LR: 1.0000, PPL: 19259.41, |Param|: 357.10, |GParam|: 37.57, Training: 12908/4802/8106 total/source/target tokens/sec
Epoch: 1, Batch: 11/184, Batch size: 12, LR: 1.0000, PPL: 19246.40, |Param|: 357.15, |GParam|: 8020223.21, Training: 12458/4655/7802 total/source/target tokens/sec
Epoch: 1, Batch: 12/184, Batch size: 64, LR: 1.0000, PPL: 17828.06, |Param|: 357.23, |GParam|: 58.06, Training: 13132/4941/8191 total/source/target tokens/sec
Epoch: 1, Batch: 13/184, Batch size: 64, LR: 1.0000, PPL: 18007.86, |Param|: 357.31, |GParam|: 167.03, Training: 13213/5149/8063 total/source/target tokens/sec
Epoch: 1, Batch: 14/184, Batch size: 64, LR: 1.0000, PPL: 20023.59, |Param|: 357.36, |GParam|: 26771927936299.44, Training: 13840/5471/8369 total/source/target tokens/sec
Epoch: 1, Batch: 15/184, Batch size: 64, LR: 1.0000, PPL: 21100.25, |Param|: 357.49, |GParam|: 2019.27, Training: 14494/5835/8658 total/source/target tokens/sec
